# Should playerNames be used to tick the timer?
ensurePlayersOnline: true

# List of player names or UUIDs that need to be online to tick the timer.
# If empty, this list will be ignored and the timer will run.
players: []

# Small utility feature, keeps spectators in spectator mode.
spectators: []

# Grace period in minutes between deaths to not update the scoreboard.
deathGracePeriod: 1

# Fix difficulty issues currently present in Fahare.
fixDifficulty: true

# If fixDifficulty is enabled, which difficulty to use.
difficulty: "HARD"

# If fixDifficulty is enabled, whether to set Hardcore mode.
isHardcore: true